version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    sorbet:
      patterns:
        - "sorbet"
        - "sorbet-*"
        - "tapioca"
        - "spoom"
        - "rbi"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
